import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#991b1b",
        "secondary-container": "#1e293b",
        "inverse-on-surface": "#0f172a",
        "on-secondary-fixed-variant": "#334155",
        "inverse-primary": "#2563eb",
        background: "#05070a",
        "on-secondary-fixed": "#f8fafc",
        "surface-container-low": "#090d16",
        "on-background": "#f1f5f9",
        "surface-bright": "#1e293b",
        "on-primary-container": "#eff6ff",
        "surface-container-highest": "#1e293b",
        "primary-fixed-dim": "#93c5fd",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#f8fafc",
        "surface-container": "#0b0f19",
        secondary: "#38bdf8",
        "on-secondary-container": "#0284c7",
        "on-tertiary-container": "#047857",
        surface: "#05070a",
        "on-tertiary-fixed": "#eff6ff",
        "primary-fixed": "#dbeafe",
        "on-error": "#ffffff",
        "tertiary-fixed": "#d1fae5",
        "on-primary-fixed-variant": "#1d4ed8",
        "surface-container-lowest": "#020408",
        outline: "#475569",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        error: "#ef4444",
        "outline-variant": "#334155",
        "tertiary-container": "#059669",
        "on-tertiary-fixed-variant": "#065f46",
        "surface-dim": "#05070a",
        "on-secondary": "#ffffff",
        "surface-variant": "#0b0f19",
        "secondary-fixed": "#e0f2fe",
        tertiary: "#10b981",
        "on-error-container": "#fca5a5",
        "on-surface-variant": "#94a3b8",
        "surface-tint": "#3b82f6",
        "secondary-fixed-dim": "#bae6fd",
        "surface-container-high": "#0f172a",
        "on-surface": "#f1f5f9",
        primary: "#3b82f6",
        "on-primary-fixed": "#1e3a8a",
        "tertiary-fixed-dim": "#a7f3d0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1280px",
        gutter: "24px",
        "unit-base": "8px",
        "margin-desktop": "80px"
      },
      fontFamily: {
        "display-lg": ["var(--font-sora)"],
        "display-lg-mobile": ["var(--font-sora)"],
        "headline-md": ["var(--font-sora)"],
        "body-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "label-caps": ["var(--font-jetbrains-mono)"]
      },
    },
  },
  plugins: [],
};
export default config;
