import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "secondary-container": "#00cbe6",
        "inverse-on-surface": "#362d3f",
        "on-secondary-fixed-variant": "#004e5a",
        "inverse-primary": "#6d3bd7",
        background: "#181021",
        "on-secondary-fixed": "#001f25",
        "surface-container-low": "#21182a",
        "on-background": "#ecddf6",
        "surface-bright": "#3f3549",
        "on-primary-container": "#340080",
        "surface-container-highest": "#3b3144",
        "primary-fixed-dim": "#d0bcff",
        "on-tertiary": "#3f2160",
        "inverse-surface": "#ecddf6",
        "surface-container": "#251c2e",
        secondary: "#5de6ff",
        "on-secondary-container": "#00515d",
        "on-tertiary-container": "#381959",
        surface: "#181021",
        "on-tertiary-fixed": "#29074a",
        "primary-fixed": "#e9ddff",
        "on-error": "#690005",
        "tertiary-fixed": "#efdbff",
        "on-primary-fixed-variant": "#5516be",
        "surface-container-lowest": "#130a1c",
        outline: "#958ea0",
        "primary-container": "#a078ff",
        "on-primary": "#3c0091",
        error: "#ffb4ab",
        "outline-variant": "#494454",
        "tertiary-container": "#a482c8",
        "on-tertiary-fixed-variant": "#573878",
        "surface-dim": "#181021",
        "on-secondary": "#00363e",
        "surface-variant": "#3b3144",
        "secondary-fixed": "#a2eeff",
        tertiary: "#dbb8ff",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#cbc3d7",
        "surface-tint": "#d0bcff",
        "secondary-fixed-dim": "#2fd9f4",
        "surface-container-high": "#2f2639",
        "on-surface": "#ecddf6",
        primary: "#d0bcff",
        "on-primary-fixed": "#23005c",
        "tertiary-fixed-dim": "#dbb8ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1280px",
        gutter: "24px",
        "unit-base": "8px",
        "margin-desktop": "80px"
      },
      fontFamily: {
        "display-lg": ["var(--font-sora)"],
        "display-lg-mobile": ["var(--font-sora)"],
        "headline-md": ["var(--font-sora)"],
        "body-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "label-caps": ["var(--font-jetbrains-mono)"]
      },
    },
  },
  plugins: [],
};
export default config;
